name: Call reusable greeting with params

on:
  workflow_dispatch:  

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      names: "Dorel,Costel,Gigi"
      greeting: "Hello,Salut,Bonjour"
      punctuation: "!,!!,!!!"