name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Îl poți rula manual din GitHub Actions

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          echo "=== Runner Info ==="
          hostname
          uname -a
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la
